import { lazy, Suspense } from 'react'
import { motion } from 'framer-motion'
import { HiArrowUpRight, HiArrowRight, HiCheck, HiBolt, HiChartBarSquare, HiCodeBracket, HiCursorArrowRays, HiGlobeAlt, HiMagnifyingGlass, HiSparkles, HiUserGroup } from 'react-icons/hi2'
import Navbar from './components/Navbar'
import SectionHeading from './components/SectionHeading'
import Counter from './components/Counter'
const ContactForm = lazy(() => import('./components/ContactForm'))

const reveal = { initial:{opacity:0,y:24}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.2}, transition:{duration:.55} }
const services = [[HiCodeBracket,'Web development','Fast, resilient websites engineered to turn attention into action.'],[HiCursorArrowRays,'UI/UX design','Interfaces that feel obvious, memorable, and unmistakably yours.'],[HiSparkles,'Brand strategy','The positioning and visual system that make your next chapter believable.'],[HiMagnifyingGlass,'SEO optimization','Technical foundations and content paths that earn durable organic demand.'],[HiBolt,'Performance marketing','Precise campaigns that learn fast and compound what works.'],[HiChartBarSquare,'Analytics','Decision-grade dashboards that make every marketing dollar legible.']]
const plans = [{name:'Starter',copy:'For ambitious teams getting their digital house in order.',price:'$4,800',features:['Conversion-focused landing page','Strategy workshop','Analytics foundation','30-day launch support']},{name:'Growth',copy:'For companies ready to make their digital presence pull its weight.',price:'$9,500',features:['Everything in Starter','Custom website up to 8 pages','Core SEO implementation','Growth experiment roadmap'],featured:true},{name:'Enterprise',copy:'For established teams with a bigger transformation in sight.',price:'Custom',features:['Everything in Growth','Complex product & platform work','Dedicated growth pod','Ongoing optimization'] }]
function HeroArt(){return <div className="hero-art" aria-hidden="true"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="art-card art-main"><div className="art-head"><span/><span/><span/></div><div className="art-lines"><i/><i/><i/></div><div className="art-chart"><b/><b/><b/><b/><b/><b/><b/></div></div><div className="art-card art-float"><span className="pulse"/><p>Growth signal</p><strong>+184%</strong></div><svg viewBox="0 0 240 160" className="art-wave"><path d="M0 120 C35 52 55 144 94 75 S160 17 240 58" fill="none" stroke="url(#grad)" strokeWidth="3"/><defs><linearGradient id="grad"><stop stopColor="#06b6d4"/><stop offset="1" stopColor="#8b5cf6"/></linearGradient></defs></svg></div>}
function Hero(){return <section id="home" className="hero"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="container hero-grid"><motion.div className="hero-copy" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="eyebrow"><span/>Independent digital agency</p><h1>We build brands people <em>choose.</em></h1><p className="lead">NovaPeak pairs sharp strategy, magnetic design and serious technology to turn your next big move into measurable momentum.</p><div className="hero-actions"><a className="primary-button" href="#contact">Build something brilliant <HiArrowRight/></a><a className="secondary-button" href="#results">Explore our impact <span>↓</span></a></div><div className="trusted"><span>Trusted by ambitious teams at</span><div><b>vertex</b><b>Northstar</b><b>ORBIT</b><b>luma</b></div></div></motion.div><motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.8,delay:.15}}><HeroArt/></motion.div></div></section>}
function Services(){return <section id="services" className="section services"><div className="container"><SectionHeading eyebrow="How we help" title={<>Built for the moments<br/>that <em>matter.</em></>}>From a new launch to a full reinvention, we bring senior thinking to the parts of your business customers can actually feel.</SectionHeading><div className="service-grid">{services.map(([Icon,title,copy],i)=><motion.article {...reveal} transition={{duration:.45,delay:i*.05}} whileHover={{y:-8}} className="service-card" key={title}><div className="icon-box"><Icon/></div><h3>{title}</h3><p>{copy}</p><a href="#contact" aria-label={`Learn more about ${title}`}>Explore <HiArrowUpRight/></a></motion.article>)}</div></div></section>}
function Why(){const features=[[HiBolt,'Fast delivery','Focused squads and clear decisions mean momentum from week one.'],[HiGlobeAlt,'Scalable systems','Built to flex with your team, traffic, and ambitions.'],[HiUserGroup,'A true extension','Senior specialists who care like they’re on your payroll.'],[HiChartBarSquare,'Data-informed','Creative instincts sharpened by evidence, never replaced by it.']];return <section className="section why"><div className="container two-col"><div><SectionHeading centered={false} eyebrow="The NovaPeak way" title={<>Good work is the<br/><em>starting line.</em></>}>We combine the pace of a nimble partner with the rigor your biggest decisions deserve.</SectionHeading><a className="underlined-link" href="#contact">Meet the team behind the work <HiArrowRight/></a></div><div className="feature-grid">{features.map(([Icon,t,c],i)=><motion.article {...reveal} transition={{delay:i*.08}} key={t}><Icon/><div><h3>{t}</h3><p>{c}</p></div></motion.article>)}</div></div></section>}
function Results(){return <section id="results" className="section results"><div className="container results-panel"><div><p className="eyebrow"><span/>The proof is in the progress</p><h2>Impact you can<br/><em>take to the board.</em></h2><p>We obsess over the kind of work that changes the trajectory of a business—not just its feed.</p><a href="#contact" className="secondary-button">See what’s possible <HiArrowRight/></a></div><div className="counter-grid"><Counter value={148} suffix="+" label="Projects launched"/><Counter value={96} suffix="%" label="Client retention"/><Counter value={42} suffix="M" label="Revenue influenced"/><Counter value={18} suffix="" label="Countries reached"/></div></div></section>}
function Testimonials(){const people=[['JM','Jordan Mitchell','Founder, Tally Health','“NovaPeak didn’t just make us look sharper—they gave our entire team a clearer story to tell.”'],['AR','Avery Reed','VP Growth, Morrow','“The rare agency that cares as much about the numbers as they do about the pixels.”'],['SK','Sana Kapoor','CMO, Arcwell','“They found the signal in a very noisy brief, then built a product our customers genuinely love.”']];return <section className="section"><div className="container"><SectionHeading eyebrow="Client notes" title={<>Kind words from<br/><em>bold companies.</em></>}/><div className="testimonial-grid">{people.map(([initials,name,role,quote],i)=><motion.figure {...reveal} transition={{delay:i*.08}} whileHover={{y:-7}} key={name}><div className="stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>{quote}</blockquote><figcaption><span className={`avatar avatar-${i}`}>{initials}</span><div><b>{name}</b><small>{role}</small></div></figcaption></motion.figure>)}</div></div></section>}
function Pricing(){return <section id="pricing" className="section pricing"><div className="container"><SectionHeading eyebrow="Simple investment" title={<>Choose your<br/><em>next altitude.</em></>}>Every engagement is designed around outcomes. These are the starting points.</SectionHeading><div className="price-grid">{plans.map(p=><motion.article whileHover={{y:-8}} className={`price-card ${p.featured?'featured':''}`} key={p.name}>{p.featured&&<span className="popular">Most popular</span>}<h3>{p.name}</h3><p>{p.copy}</p><strong>{p.price}<small>{p.price[0]==='$'?' / project':''}</small></strong><a href="#contact" className={p.featured?'primary-button':'secondary-button'}>Let’s talk <HiArrowRight/></a><ul>{p.features.map(x=><li key={x}><HiCheck/>{x}</li>)}</ul></motion.article>)}</div></div></section>}
function FAQ(){const qs=[['What does a typical project look like?','Most engagements start with a focused strategy sprint, then move into design and build. You’ll have a single senior point of contact and a transparent weekly rhythm throughout.'],['How quickly can we get started?','We keep a small number of active partnerships so our teams stay attentive. We can usually start discovery within two to four weeks.'],['Do you work with in-house teams?','Absolutely. We often plug into existing marketing, product and engineering teams, bringing a specialist perspective without creating extra layers.'],['Can you help after launch?','Yes. Growth is where the interesting work begins. We offer ongoing optimization, experimentation and performance partnerships.']];return <section className="section faq"><div className="container two-col"><SectionHeading centered={false} eyebrow="Common questions" title={<>Clear answers,<br/><em>no agency fog.</em></>}>If you’re weighing up a digital partner, these are usually the first things people want to know.</SectionHeading><div>{qs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>}
function Contact(){return <section id="contact" className="section contact"><div className="container contact-panel"><div><p className="eyebrow"><span/>Your next chapter starts here</p><h2>Ready when<br/>you <em>are.</em></h2><p>Tell us what’s on the horizon. We’ll bring the questions, ideas, and occasionally very good coffee.</p><a href="mailto:hello@novapeak.studio" className="email-link">hello@novapeak.studio <HiArrowUpRight/></a></div><Suspense fallback={<div className="form-loading" aria-label="Loading contact form"/>}><ContactForm/></Suspense></div></section>}
function Footer(){return <footer><div className="container footer-grid"><div><a className="logo" href="#home"><i>✦</i> NOVAPEAK</a><p>Strategy, design and technology for companies headed somewhere interesting.</p></div><div><h3>Explore</h3><a href="#services">Services</a><a href="#results">Results</a><a href="#pricing">Pricing</a></div><div><h3>Connect</h3><a href="mailto:hello@novapeak.studio">Email us</a><a href="#contact">Start a project</a><a href="#home">LinkedIn</a></div><div className="footer-note"><p>© {new Date().getFullYear()} NovaPeak Studio.</p><p>Built for <a href="https://digitalheroesco.com" target="_blank" rel="noreferrer">Digital Heroes</a> Training Task</p></div></div></footer>}
export default function App(){return <><Navbar/><main><Hero/><Services/><Why/><Results/><Testimonials/><Pricing/><FAQ/><Contact/></main><Footer/></>}
